stages:
  - test
  - report

API:
  image: circleci/node:13
  stage: test
  before_script:
    - npm install
  script:
    - npm test
  after_script:
    - sh .notify.sh
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - jest_html_reporters.html
UI:
  image: mcr.microsoft.com/playwright:bionic
  stage: test
  before_script:
    - npm install
  script:
    - npx codeceptjs run --steps --plugins allure
  after_script:
    - sh .notify.sh
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - output

allure_job:
  stage: report
  tags:
    - docker
  image: frankescobar/allure-docker-service
  script:
    - allure generate -c ./output -o ./allure-report
  artifacts:
    paths:
      - ./output
      - ./allure-report
    expire_in: 1 day
  rules:
    - when: always

pages:
  stage: report
  script:
    - mkdir public
    - mv ./jest_html_reporters.html public
  artifacts:
    paths:
      - public
  rules:
    - when: always
