stages:
  - test
  - report

API:
  image: circleci/node:13
  stage: test
  before_script:
    - npm install
  script:
    - npm test
  after_script:
    - sh .notify.sh
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - jest_html_reporters.html
UI:
  image: mcr.microsoft.com/playwright:bionic
  stage: test
  before_script:
    - npm install
  script:
    - npx codeceptjs run --steps --plugins allure
    - ls
  after_script:
    - sh .notify.sh
    - ls
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - allure-report
pages:
  stage: report
  script:
    - mkdir public
    - mv ./jest_html_reporters.html public
  artifacts:
    paths:
      - public
  rules:
    - when: always
