stages:
  - test
  - report
  - reportpublic

API:
  image: circleci/node:13
  stage: test
  before_script:
    - npm install
  script:
    - npm test --steps --plugins allure
  after_script:
    - sh .notify.sh
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - output1
UI:
  image: mcr.microsoft.com/playwright:bionic
  stage: test
  before_script:
    - npm install
  script:
    - npx codeceptjs run --steps --plugins allure
  after_script:
    - sh .notify.sh
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - output2

allure_job:
  stage: report
  tags:
    - docker
  image: frankescobar/allure-docker-service
  script:
    - allure generate -c ./output1 -o ./allure-report1
    - allure generate -c ./output2 -o ./allure-report2
  artifacts:
    paths:
      - ./output1
      - ./allure-report1
      - ./output2
      - ./allure-report2
    expire_in: 1 day
  rules:
    - when: always

pages:
  stage: reportpublic
  script:
    - mkdir public
    - mv ./allure-report2/* public

  artifacts:
    paths:
      - public
  rules:
    - when: always
