stages:
  - deploy
  - test

trigger_build:
  stage: deploy
  script:
    - "curl -X POST -F token='bef9f82c5663bed501133bdbb90bb2' -F ref=codecept https://gitlab.com/api/v4/projects/24501886/trigger/pipeline"

QA:
  image: circleci/node:13
  stage: test
  before_script:
    - npm install
  script:
    - npm test
  after_script:
    - sh .notify.sh
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - jest_html_reporters.html
